apiVersion: v1
kind: Service
metadata:
  name: parliament-notification
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app.kubernetes.io/name: parliament-notification